services:
  app:
    build: .
    image: crafting-sample-app
    restart: unless-stopped
    ports:
      - "3008:3000"
    volumes:
      - ./.env:/usr/src/app/.env
    environment:
      NODE_ENV: development
